### PR TITLE
Modernize Bible reference format

### PR DESCRIPTION
**Pull request by bentley**

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

Do you think it would be possible to check for these in a generic sense with a regex? If so, we could add a check like this to `se lint`.

**Comment by bentley** [comment]
It’s a difficult problem. There’s a lot of variation: uppercase versus lowercase, very short abbreviations (how safe is it to say “Gen. X” or “Lev. VI” refer specifically to the Biblical books?), almost uncountable alternate names (“Acts” versus “Acts of the Apostles,” “Luke” versus “the Gospel of Luke” versus “Luke’s gospel,” “Revelation” versus “Revelations” versus “The Apocalypse of John”…). We might be able to detect common cases for more distinctive books like Genesis or Exodus, but names like John or Peter are often followed by Roman numerals in the names of kings or popes.

I’m manually inspecting all uses of `z3998:roman` with a few exclusionary regexes, because I can’t think of a better way.

**Comment by bentley** [comment]
Adding it to the manual is the best method I can think of, because then they’re likely to be caught by producers and proofreaders.

**Comment by bentley** [comment]
Oh, I see that was already added to the manual recently.

**Comment by acabal** [comment]
We don't have to be exact and catch every single permutation. Just a rule that catches things in the general sense is enough, and if some outlier examples get past us that's fine. I think it would be very helpful to put together a regex like that. Can you maybe give it a shot to see what you come up with? This will go in an xpath expression like the rest of the lint checks, and the benefit of that is that you don't have to worry about tags in a regex.

**Comment by acabal** [comment]
Something as basic as a list of common Bible book names, followed by a roman semantic, followed by an Arabic numeral might be enough to catch 75% or more of these cases. And once a producer is alerted to the existence of old style citations, they can be on the lookout for others that lint didn't catch.

**Pull request merged**
